ISO_11801_Cable = CableShield '/' PairShield CableTyp;
CableShield = Unshielded | Screened | Shielded Foiled;
PairShield = Unshielded | Shielded | Foiled;
CableType = TwistedPair | QuadPair;
Unshielded = 'U';
Screened = 'S';
Shielded = 'S';
Foiled = 'F';
TwistedPair = 'TP';
QuadPair = 'QP';
