json = element ; (* R1 *) 
element = ws value ws ; (* R2 *)
value = obj | arr | str | num | 'true' | 'false' | 'null'; (* R3 *)
obj = '{' ws '}' | '{' ws members ws '}'; (* R4 *)
members = member | member ',' members; (* R5 *)
member = ws string ws ':' element; (* R6 *)
arr = '[' ws ']' | '[' elements ']'; (* R7 *)
elements = element | element ',' elements; (* R8 *)
ws = '' | '0020' ws | '000A' ws | '000D' ws | '0009' ws; (* R9 *)

(* nach https://www.json.org/json-en.html *)

(* Anwendung: *)

json = '{ }';              (* R1 > R2 > R3 > R4 *)
json = '[ ]';              (* R1 > R2 > R3 > R7 *)
json = '"stimme": "hoch"'; (* R1 > ? > R6 : members nur in obj R4 *)
json = 'true';             (* R1 > R2 > R3 *)
